### PR TITLE
[WIP] Design updates

### PR DESCRIPTION
**Pull request by silvenon**
I would like to improve the website's design. Before I start, here's my plan:

- use `@2x` and SVG graphics everywhere for Retina screens
- align social buttons on the home page better
- maybe use white background everywhere, then use a colored background to distinguish parts like "Extendable/Compatible/Feature-Rich" on the home page
- improve typography (increase line height etc.)
- modernize site generation a bit, use node-sass instead of Ruby Sass etc.

If you don't like some of these ideas and/or have additional ideas, please share!

### CODE REVIEW

**Comment by christian-bromann** [comment]
@silvenon I like these ideas 👍 . Let's also replace the logo with a real SVG icon and maybe with #41

**Comment by christian-bromann** [comment]
Another issue: the twitter profile images are quite big, might be a good idea to have them in the repository or find a smaller version of these images.

**Comment by silvenon** [comment]
@christian-bromann sure! I'm a file size control-freak, so I'll optimize what I can.

**Comment by silvenon** [comment]
@christian-bromann do you have the SVG version of the logo?

**Comment by christian-bromann** [comment]
@silvenon yes: http://webdriverjs.christian-bromann.com/brobot.svg

**Comment by christian-bromann** [comment]
@silvenon any updates? 

How about having the menu for mobile similar to http://jump-berlin.de

**Comment by silvenon** [comment]
@christian-bromann hey, so sorry about the delay. I'm having trouble taming Hexo, I want to modify the environment so I can run a single command and get:

* server running
* files recompiling on change
* CSS recompiling on change, along with the errors

But I can't seem to do it, I need 4 Terminal windows in total. Hexo is 4th static site generator on [StaticGen](https://www.staticgen.com/), but many aspects seem really neglected.

If you want me to build a friendlier environment, I can move to a different generator like [Harp](https://harpjs.com/docs/quick-start) (making sure you can still work with EJS).

If that would be too much for you, feel free to say so and I'll manage with the current setup. 😉

**Comment by christian-bromann** [comment]
> I'm having trouble taming Hexo

What other problems do you have then having to open 3 terminal windows for recompiling stuff? Maybe we can use https://www.npmjs.com/package/concurrently to have that in one command. Maybe we could enhance the [hexo-wdio-generator](https://github.com/webdriverio/hexo-wdio-generator) to run that in parallel.

I don't mind switching to a different static page generator I just think you will end up making yourself more work then making the dev environment in hexo more friendly. The current deployment setup with hexo and hexo-wdio-generator works pretty good and generates the docs for all versions. I might have been lazy in terms of documentation so feel free to ping me at any time.

**Comment by silvenon** [comment]
> I don't mind switching to a different static page generator I just think you will end up making yourself more work then making the dev environment in hexo more friendly.

I see what you mean, but here are some other stuff that were off-putting:

- I want Autoprefixer, but the only way to have Sass with Autoprefixer seems to be [hexo-renderer-sass-autoprefixer](https://github.com/mshick/hexo-renderer-sass-postcss), i.e. you have to create a renderer which processes them exactly in that order. I tried using it, expecting it to shout at me that Compass is missing, but instead it just silently created an empty CSS, so I probably have to create my own renderer.
- Where is the `hexo wdio compass` command coming from? I didn't find any clue for this behavior in Hexo's docs.

I know we can hack all the processes to work as a single command, but I'd like to create a more future-proof solution which could invite more contributions. Of course, my main guideline would be to not sacrifice any of the existing simplicity.

**Comment by christian-bromann** [comment]
> Where is the hexo wdio compass command coming from?

It is all in the [hexo wdio](https://github.com/webdriverio/hexo-wdio-generator/blob/master/lib/build.js#L101-L106) plugin I made

> but I'd like to create a more future-proof solution which could invite more contributions.

Like I said, I don't mind switching to something more sophisticated and future proof. I leave it up to you.

**Comment by silvenon** [comment]
> It is all in the hexo wdio plugin I made

Oh, that explains it! 😅 

> Like I said, I don't mind switching to something more sophisticated and future proof. I leave it up to you.

I'll think about it some more and try different stuff.

**Comment by silvenon** [comment]
I'll close it because I have no idea when I will get around to doing this. Sorry. 😅

**Pull request closed without merging**
