### PR TITLE
feat(docsearch): add docsearch

### PR DESCRIPTION
**Pull request by vvo**
Not yet to be merged, need more work

### CODE REVIEW

**Comment by vvo** [comment]
Yo @LukyVj. This is a docsearch implementation but it looks crappy. Would be awesome to have your input and maybe redo what you did on middleman website.

You can work on this PR by doing this:

```sh
# Fork the repo on your account
git clone git@github.com:LukyVj/webdriver.io.git
git checkout -b new-docsearch
git remote add upstream git@github.com:webdriverio/webdriver.io.git
git fetch upstream docsearch
git merge upstream/docsearch
# Then follow instructions here: https://github.com/webdriverio/webdriver.io#requirements
# See changed files to see where to add code https://github.com/webdriverio/webdriver.io/pull/41/files
# Seems like when the server is running, you need to relaunch compass command step by hand
# Then push to your fork, open a new PR
```

We can also work on that next week, see ya

**Comment by LukyVj** [comment]
Hey! Sure! I'll dive into it on monday!

**Comment by christian-bromann** [comment]
@vvo @LukyVj any updates? Anything I can help with?

**Comment by vvo** [comment]
@christian-bromann If you run the project, you will see the search experience we created. And if you are able to style it properly to fits the website that would be awesome.

**Comment by silvenon** [comment]
@vvo I can help, I love styling! 🎨 I'll notify within a day or two when if I made some progress.

**Comment by vvo** [comment]
woah @silvenon that would be awesome, let me know if you have some issues while doing so

**Comment by silvenon** [comment]
With the current build system it's hard to iterate design (e.g. I have to run the compass command every time I want to see the update), so I'll first refactor with node-sass + live reload.

**Comment by christian-bromann** [comment]
@silvenon I used to run compass in watch mode

**Comment by silvenon** [comment]
@christian-bromann I'll try that, because with node-sass I can't use Compass, but Compass is used for image sprites, so removing it out would be too big of a change for now.

**Comment by silvenon** [comment]
How's this?

screen shot 2016-11-07 at 02 01 52

**Comment by christian-bromann** [comment]
man .. that looks awesome!

**Comment by christian-bromann** [comment]
@silvenon I added you as collaborator so feel free to push to the same branch.

**Comment by silvenon** [comment]
@christian-bromann thanks! I don't have push access to this particular repository, though.

**Comment by vvo** [comment]
WOA! Awesome design skills @silvenon :)

**Comment by vvo** [comment]
Yep @silvenon seems like you are now a collaborator, otherwise I will just make the adjustement!

**Comment by silvenon** [comment]
Rebased (because of a conflict) and pushed.

**Comment by vvo** [comment]
@christian-bromann I'll let you review the additional changes to the website build and merge/release. That would be great!

**Comment by silvenon** [comment]
My first two commits aren't a complete story, I'll finish that idea in #42.

**Comment by silvenon** [comment]
Removed the Autoprefixer stuff, I'll fix that stuff in #42.

**Comment by christian-bromann** [comment]
LGTM
@silvenon is there anything left to do here or can we merge it?

**Comment by silvenon** [comment]
@christian-bromann I think not everything is indexed, for example I think that typing "Configuration" should also return Get Started > Configuration, but design-wise it's ok to merge.

@vvo is there something we can do about the index? I'm not sure how DocSearch works exactly.

**Comment by vvo** [comment]
> @vvo is there something we can do about the index? I'm not sure how DocSearch works exactly.

Yes we can definitely work on the index configuration, I am not as familiar as you maybe as browsing the webdriver.io website. If you can open a new issue detailing the current issues the index has, I can then work on it. Algolia https://www.algolia.com/ maintains the index for free and I am an employee of Algolia so index tuning is doable, we did it for other projects.

**Comment by christian-bromann** [comment]
Will deploy the changes with a new WebdriverIO update later today.

**Comment by vvo** [comment]
WEeee!!

**Pull request merged**
